---
title: ""
author: "Adani B. Abutto"
date: "`r Sys.Date()`"

output:
  bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
    highlight: tango

header-includes:
    - \usepackage{setspace}\doublespacing
---

```{r setup, include = F, message = F, warning = F}

## load relevant libraries and functions
require(knitr)         # for knitting
library(DT)            # for datatable() function
library(png)           # for working with images
library(grid)
library(patchwork)     # for multiple plots
library(tidyverse)     # for everything else
library(ggpubr)
library(dplyr)

## set default code chunk options
knitr::opts_chunk$set(echo = T, warning = F, message = F)

## set default plot theme 
theme_set(theme_classic() + 
            theme(text = element_text(size = 24))) 

## fix print width for knitted doc
options(width = 70)

## set random seed
set.seed(1)

## set directories for plots and data outputs
figures_dir = '../../plots'
```

# Data Import

```{r}

df.raw =
  as_tibble(read_csv("platform_data.csv"))

df.processed =
  df.raw %>%
  select(Platform, Year, DAU, MAU) %>%
  mutate(DAU = case_when(DAU %in% c("-", "N/A", "NA", "") ~ NA_real_,
                         TRUE ~ as.numeric(gsub(",", "", DAU))),
         MAU = case_when(MAU %in% c("-", "N/A", "NA", "") ~ NA_real_,
                         TRUE ~ as.numeric(gsub(",", "", MAU)))) %>%
  mutate(Platform = as.factor(Platform))

```

# Plot

```{r fig.width = 11, fig.height = 8}

df.long =
  df.processed %>%
  pivot_longer(cols = c(DAU, MAU),
               names_to = "metric_type",
               values_to = "count")
plot1 = 
  df.long %>%
  filter(metric_type == "MAU") %>%
  filter(Platform != "Reddit") %>%
  ggplot(aes(x = Year,
             y = count,
             color = Platform,
             fill = Platform,
             group = Platform)) +
  geom_line(linewidth = 1, na.rm = F) +
  geom_point(size = 3, shape = 21, color = "black", na.rm = F) +
  scale_y_continuous(breaks = seq(0, ceiling(max(df.long$count,
                                                 na.rm = TRUE) /
                                               100000000) * 100000000, 
                                  by = 200000000),
                     labels = scales::comma) +
  scale_x_continuous(breaks = seq(2004, 2026, by = 1),
                     limits = c(2004, 2026)) +
  labs(x = "Year",
       y = "Monthly Active User Count",
       color = "Platform",
       fill = "Platform") +
  theme_classic(base_size = 24) +
  theme(strip.text = element_text(size = 24, face = "bold"),
        axis.text.x = element_text(angle = 70, hjust = 1),
        legend.position = "top")

plot1

ggsave((paste0(figures_dir, "user_base.png")),
       plot = plot1,
       width = 11, height = 8, device = "png")

```
